# Website's icon url.
favicon: /img/IK.png 
# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

rss: /atom.xml

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo:
  text: Huangzl's blog

article:
  # Show word count and estimated reading time.
  readtime: false
  # Code highlight theme
  highlight: prism-tomorrow

# Navigation bar menu links.
menu:
  文章列表: /archives
  分類: /categories
  推薦閱讀: /recommend
  關於我: /abouts

# Search plugin settings.
search:
  #type: google-cse
  #cx: 000864066023191638225:bkiqcm81ija

# Navigation bar toc settings
toc: true

# Share plugin settings.
share:
  #type: sharethis
  #install_url: https://platform-api.sharethis.com/js/sharethis.js#property=5d8b39b069ba670012bf92b9&product=inline-share-buttons

# Comment plugin settings.
comment:
  type: utterances

# Other plugins and their settings.
plugins:
  mathjax: false
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id: 'G-1393J2EVCZ'

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:

  Facebook:
    icon: fab fa-twitter
    url: https://twitter.com/hungzln3

  RSS:
    icon: fas fa-rss
    url: /atom-ch.xml

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/ikkkp
